import type { MembershipPlan } from "@/types/membership";

/**
 * Typed fallback used only when the backend plan list is unavailable.
 * Values mirror the canonical membership_plans rows exactly.
 */
export const FALLBACK_MEMBERSHIP_PLANS: MembershipPlan[] = [
  {
    id: "fallback-essential",
    slug: "essential",
    name: "Essential",
    tagline: "Great starter plan",
    monthlyPriceCents: 29900,
    currency: "TTD",
    monthlyWashLimit: 2,
    monthlyInteriorLimit: 0,
    discountPercentage: 10,
    rewardMultiplier: 2,
    vehicleLimit: 1,
    features: [
      "2 Maintenance Washes",
      "Interior Vacuum",
      "Dashboard Wipe",
      "Tire Shine",
      "Glass Cleaning",
      "10% Service Discount",
      "Double Reward Points",
    ],
    limits: ["Max 2 visits monthly", "One registered vehicle", "No rollover visits"],
    tierRank: 1,
    isFeatured: false,
    requiresQuote: false,
  },
  {
    id: "fallback-premium",
    slug: "premium",
    name: "Premium",
    tagline: "Most popular",
    monthlyPriceCents: 49900,
    currency: "TTD",
    monthlyWashLimit: 4,
    monthlyInteriorLimit: 1,
    discountPercentage: 15,
    rewardMultiplier: 2,
    vehicleLimit: 1,
    features: [
      "4 Maintenance Washes",
      "Premium Interior Detail",
      "Spray Sealant",
      "Priority Booking",
      "15% Service Discount",
      "Double Reward Points",
    ],
    limits: ["Max 4 visits monthly", "One registered vehicle", "No rollover visits"],
    tierRank: 2,
    isFeatured: true,
    requiresQuote: false,
  },
  {
    id: "fallback-platinum",
    slug: "platinum",
    name: "Platinum",
    tagline: "The full experience",
    monthlyPriceCents: 79900,
    currency: "TTD",
    monthlyWashLimit: 5,
    monthlyInteriorLimit: 2,
    discountPercentage: 20,
    rewardMultiplier: 3,
    vehicleLimit: 1,
    features: [
      "5 Maintenance Washes",
      "2 Deep Interior Cleans",
      "Ceramic Booster",
      "Rain Repellent",
      "Priority Scheduling",
      "20% Service Discount",
      "Triple Reward Points",
      "Annual Paint Inspection",
    ],
    limits: ["Max 5 maintenance visits", "Max 2 interior details", "One registered vehicle"],
    tierRank: 3,
    isFeatured: false,
    requiresQuote: false,
  },
  {
    id: "fallback-family",
    slug: "family",
    name: "Family",
    tagline: "3 vehicles",
    monthlyPriceCents: 99900,
    currency: "TTD",
    monthlyWashLimit: 8,
    monthlyInteriorLimit: 2,
    discountPercentage: 15,
    rewardMultiplier: 2,
    vehicleLimit: 3,
    features: [
      "3 Registered Vehicles",
      "8 Shared Maintenance Washes",
      "15% Service Discount",
      "Priority Scheduling",
      "Double Reward Points",
    ],
    limits: ["8 shared washes/month", "Up to 3 vehicles", "No rollover visits"],
    tierRank: 4,
    isFeatured: false,
    requiresQuote: false,
  },
  {
    id: "fallback-fleet",
    slug: "fleet",
    name: "Fleet",
    tagline: "5+ vehicles, custom",
    monthlyPriceCents: 0,
    currency: "TTD",
    monthlyWashLimit: 0,
    monthlyInteriorLimit: 0,
    discountPercentage: 20,
    rewardMultiplier: 2,
    vehicleLimit: 5,
    features: [
      "5+ Registered Vehicles",
      "Dedicated Account Manager",
      "Monthly Reporting",
      "Flexible Billing",
      "Custom Visit Allowance",
    ],
    limits: ["Custom allowance agreed per contract", "Minimum 5 vehicles"],
    tierRank: 5,
    isFeatured: false,
    requiresQuote: true,
  },
];
